# Generated by Django 4.1.7 on 2023-02-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='cover_url',
            new_name='cvr_url',
        ),
    ]
